name: CI Ubuntu (Ninja + GHCR)

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

env:
  CMAKE_GENERATOR: Ninja

jobs:
  # ====================================================================
  # Construct the Docker image and push it to GHCR
  # ====================================================================
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    outputs:
      image_uri: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Convert repository name to lowercase
        run: |
          echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Connect to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/ubuntu-gcc
          tags: |
            type=raw,value=latest
      - name: Build and Push the Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/debian/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ====================================================================
  # Build and Test the Project
  # ====================================================================
  build:
    needs: build-docker
    if: needs.build-docker.result == 'success' || needs.build-docker.result == 'skipped'
    runs-on: ubuntu-latest

    container: ${{ needs.build-docker.outputs.image_uri }}
    strategy:
      matrix:
        build-type: [Release, Debug]
        include:
          - build-type: Release
            preset: release-ninja-linux
          - build-type: Debug
            preset: debug-ninja-linux

    steps:
      # ====================================================================
      # Checkout
      # ====================================================================
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # ====================================================================
      # Configure cmake environment
      # ====================================================================
      - name: Configure CMake Project
        id: configure
        run: |
          TESTS_FLAG=""
 
          if [ -d "tests" ] && [ "$(ls -A tests 2>/dev/null)" ]; then
            TESTS_FLAG="-DBUILD_TESTS=ON"
            echo "::notice file=tests::the directory 'tests' exists and is not empty. Tests enabled."
          else
            echo "::warning file=tests::the directory 'tests' is empty or missing. Tests disabled"
          fi

          cmake \
          --preset ${{ matrix.preset }} \
          -DBUILD_DESKTOP_UI:BOOL=ON \
          ${TESTS_FLAG} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DCMAKE_PREFIX_PATH=/opt/qt/6.10.2/gcc_64
        shell: bash

      # ====================================================================
      # Build
      # ====================================================================
      - name: Build Project
        run: |
           cmake --build build/${{ matrix.preset }} --config ${{ matrix.build-type }} --parallel $(nproc)
        shell: bash

      # ====================================================================
      # Test
      # ====================================================================
      - name: Run Tests
        if: ${{ always() && steps.configure.outcome == 'success' }}
        run: |
          cd build/${{ matrix.preset }}
          ctest --output-on-failure -C ${{ matrix.build-type }}
        shell: bash

      # ====================================================================
      # Upload build artifacts
      # ====================================================================
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-ubuntu-${{ matrix.build-type }}
          path: |
            build/${{ matrix.preset }}/qt/desktop/imaginator_desktop
          retention-days: 7
          if-no-files-found: warn
