name: CI Windows (vcpkg + MSVC)

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
  USERNAME: ${{ github.repository_owner }}
  FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,readwrite"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 70

    permissions:
      packages: write

    strategy:
      matrix:
        build-type: [Release, Debug]
        include:
          - build-type: Release
            preset: release-vcpkg-msvc
          - build-type: Debug
            preset: debug-vcpkg-msvc

    steps:
      # ====================================================================
      # Checkout
      # ====================================================================
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # ====================================================================
      # Setup Vulkan SDK
      # ====================================================================
      - name: Install Vulkan SDK
        run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe" -OutFile "vulkan-sdk.exe"
          Start-Process -FilePath "./vulkan-sdk.exe" -Args "--accept-licenses --default-answer --confirm-command install" -Wait

      # ====================================================================
      # Setup Qt
      # ====================================================================
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
         version: '6.10.2'
         target: 'desktop'
         arch: 'win64_msvc2022_64'

      # ====================================================================
      # Setup vcpkg
      # ====================================================================
      - name: Setup vcpkg (latest)
        run: |
          cd C:\vcpkg

          Write-Host "Fetching specific baseline..."
          git fetch origin cd61e1e26a038e82d6550a3ebbe0fbbfe7da78e3

          Write-Host "Checking out project baseline..."
          git checkout cd61e1e26a038e82d6550a3ebbe0fbbfe7da78e3

          Write-Host "Bootstrapping vcpkg..."
          .\bootstrap-vcpkg.bat

          Write-Host "Setting environment variables..."
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
          echo "C:\vcpkg" >> $env:GITHUB_PATH

      # ====================================================================
      # Configuration of NuGet source for vcpkg cache
      # ====================================================================
      - name: Configure NuGet source for vcpkg cache
        shell: pwsh
        run: |
          $nugetExe = & "$env:VCPKG_ROOT\vcpkg.exe" fetch nuget | Select-Object -Last 1
          Write-Host "Using NuGet executable: $nugetExe"

          & $nugetExe sources add `
            -Source "$env:FEED_URL" `
            -StorePasswordInClearText `
            -Name "GitHubPackages" `
            -UserName "$env:USERNAME" `
            -Password "${{ secrets.GITHUB_TOKEN }}"

          & $nugetExe setapikey "${{ secrets.GITHUB_TOKEN }}" -Source "$env:FEED_URL"

      # ====================================================================
      # Configure & Build with CMake
      # ====================================================================
      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: '${{ matrix.preset }}'
          configurePresetAdditionalArgs: "['-Ddesktop_ui=ON','-Dtests=OFF']"
          buildPreset: '${{ matrix.preset }}'
          buildPresetAdditionalArgs: "['--config ${{ matrix.build-type }}']"

      # ====================================================================
      # Upload build artifacts
      # ====================================================================
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.build-type }}
          path: |
            build/qt/desktop/${{ matrix.build-type }}/*.exe
            build/bin/*.dll
          retention-days: 7
          if-no-files-found: ignore

